
version: '2.0'

services:
    Website1:
        image: ghcr.io/samoht89/website1:latest #change samoht89 to your username and website1 to your respitory name
        deploy:
        labels: [com.centurylinklabs.watchtower.enable=true]
        container_name: website1 #Your firstname-"usernameAtSchool"
        restart: always
        ports:
            - "80:80" #Change first port if using nginx
